kind: ConfigMap
metadata:
    creationTimestamp: null
    name: prometheus-core
    namespace: monitoring
apiVersion: v1
data:
    prometheus.yaml: |
        global:
            scrape_interval: 15s
            scrape_timeout: 15s
            evaluation_interval: 15s
        alerting:
            alertmanagers:
            - static_configs:
                - targets: ["10.254.127.110:9093"]
        rule_files:
            - "/etc/prometheus-rules/*.yml"
        scrape_configs:
        - job_name: 'kubernetes-apiservers'
            kubernetes_sd_configs:
            - role: endpoints
            scheme: https
            tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: default;kubernetes;https
