apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  namespace: atai-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      labels:
        app: gitlab-runner
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-115
      terminationGracePeriodSeconds: 10
      hostNetwork: true
      containers:
      - args:
        - run
        image: gitlab/gitlab-runner:alpine-v14.3.1
        imagePullPolicy: IfNotPresent
        name: gitlab-runner
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: config
        - mountPath: /var/run/docker.sock
          name: docker
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: config
        name: config
      - hostPath:
          path: /var/run/docker.sock
        name: docker
