apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: atai-testing-kibana
  namespace: elastic-system
spec:
  version: 7.12.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: atai-testing-eck-cluster
  config:
    xpack.security.enabled: false    
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 4Gi
        readinessProbe:
           failureThreshold: 3
           httpGet:
             path: /
             port: 5601
             scheme: HTTP
           initialDelaySeconds: 10
           periodSeconds: 10
           successThreshold: 1
           timeoutSeconds: 5
