apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 172.17.20.111
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.5
controlPlaneEndpoint: "172.17.20.116:7443"
imageRepository: registry.aliyuncs.com/google_containers
apiServer:
  certSANs:
    - k8s-01
    - k8s-02
    - k8s-03
    - k8s-04
    - k8s-05
    - 172.17.20.111
    - 172.17.20.112
    - 172.17.20.113
    - 172.17.20.114
    - 172.17.20.115
    - 172.17.20.116
    - 127.0.0.1
dns:
  type: CoreDNS
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
