- name: Copy templated configures
  template:
    src: "{{role_path}}/files/configures/beats/{{item}}-{{group_names[0]}}.yml"
    dest: "/etc/{{item}}/{{item}}.yml"
    mode: 0600
  loop: "{{ beats }}"
