apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: postgresdb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/postgresdb
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
