apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner
  namespace: atai-ops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-disk
  volumeMode: Filesystem
  volumeName: gitlab-runner
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  phase: Bound


