kind: Service
apiVersion: v1
metadata:
  name: external-mssql
  namespace: db
spec:
  ports:
    - name: db
      protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433
  selector:
    app: sqlserver
  type: NodePort
  sessionAffinity: None
