apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skywalking
  labels:
    app: oap-dotnet
  name: oap-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oap-dotnet
  template:
    metadata:
      labels:
        app: oap-dotnet
    spec:
      volumes:
        - name: oap
          configMap:
            name: oap
      containers:
        - name: oap-dotnet
          imagePullPolicy: IfNotPresent
          image: 'apache/skywalking-oap-server:7.0.0-es7'
          ports:
            - name: server
              protocol: TCP
              containerPort: 11800
            - name: ui
              protocol: TCP
              containerPort: 12800
          volumeMounts:
            - name: oap
              readOnly: true
              mountPath: /skywalking/config/alarm-settings.yml
              subPath: alarm-settings.yml
          env:
            - name: SW_STORAGE
              value: elasticsearch7
            - name: SW_STORAGE_ES_CLUSTER_NODES
              value: 'atai-testing-eck-cluster-es-http.elastic-system:9200'
            - name: SW_STORAGE_ES_RECORD_DATA_TTL
              value: '2'
            - name: SW_STORAGE_ES_OTHER_METRIC_DATA_TTL
              value: '2'
            - name: TZ
              value: Asia/Shanghai
            - name: SW_NAMESPACE
              value: dotnet
          resources:
            limits:
              cpu: 500m
              memory: 2048Mi
            requests:
              cpu: 200m
              memory: 1024Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: oap-dotnet-service
  namespace: skywalking
  labels:
    app: oap-dotnet
spec:
  type: NodePort
  selector:
    app: oap-dotnet
  ports:
    - name: service
      port: 11800
      protocol: TCP
      targetPort: 11800
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: oap-dotnet-ui
  namespace: skywalking
  labels:
    app: oap-dotnet
spec:
  type: ClusterIP
  selector:
    app: oap-dotnet
  ports:
    - name: ui
      port: 12800
      protocol: TCP
      targetPort: 12800
