---

- name: Check number of nodes in the cluster
  shell: "curl -s -m 2 'localhost:9200/_cat/nodes?h=name' | wc -l"
  register: nodes_count

- name: Turn off shard reallocation
  shell: "curl -XPUT localhos:9200/_cluster/settings -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : \"none\" }}'"
  register: response
  failed_when: response.stdout.find('"acknowledged":true') == -1

- name: Stop the elasticsearch service
  service:
    name: elasticsearch
    state: stopped
  sudo: True

- name: Start the elasticsearch service
  service:
    name: elasticsearch
    state: started
  sudo: True

- name: Wait for the node to rejoin the cluster
  shell: "curl -s -m 2 'localhost:9200/_cat/nodes?h=name' | wc -l"
  register: new_nodes
  until: new_nodes.stdout == nodes_count.stdout
  retries: 200
  delay: 3

- name: Turn on shard allocation
  shell: "curl -XPUT localhost:9200/_cluster/settings -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : \"all\" }}'"
  register: response
  failed_when: response.stdout.find('"acknowledged":true') == -1

- name: Wait until cluster status is green
  shell: "curl -XGET localhost:9200/_cluster/health"
  register: response
  until: response.stdout.find('"status":"green"') != -1
  retries: 100
  delay: 10
