apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    field.cattle.io/creatorId: user-9h4rp
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: prometheus1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/kubesphere/data1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Available

---

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    field.cattle.io/creatorId: user-9h4rp
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: prometheus2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/kubesphere/data2
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Available

---

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    field.cattle.io/creatorId: user-9h4rp
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    cattle.io/creator: norman
  name: minio1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/kubesphere/data3
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Available


