apiVersion: logging.kubesphere.io/v1alpha2
kind: Filter
metadata:
  labels:
    logging.kubesphere.io/component: atai-app
    logging.kubesphere.io/enabled: "true"
  name: filter-java
  namespace: kubesphere-logging-system
spec:
  filters:
  - parser:
      keyName: log
      parser: json
  - modify:
      conditions:
      - keyDoesNotExist:
          AuditID: ""
      rules:
      - add:
          ignore: "true"
  - grep:
      exclude: ignore true
  match: atai-app
