apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: redis-vip-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/redis/vip/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: redis-vip-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/redis/vip/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: redis-vip-3
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/redis/vip/
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem


