apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: apisix-0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk 
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/apisix
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: apisix-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/apisix
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem                       
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: apisix-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-disk
  capacity:
    storage: 8Gi
  hostPath:
    path: /data/apisix
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apisix-etcd-0
  namespace: ingress-apisix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-disk
  volumeMode: Filesystem
  volumeName: apisix-0
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apisix-etcd-1
  namespace: ingress-apisix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-disk
  volumeMode: Filesystem
  volumeName: apisix-1
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-apisix-etcd-2
  namespace: ingress-apisix
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-disk
  volumeMode: Filesystem
  volumeName: apisix-2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
